spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/springbootjpa?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
#    username: root
#    password: whdrjffbs12!
#    driver-class-name: com.mysql.cj.jdbc.Driverspring:

  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      #어플리케이션 실행시점에  가지고 있는 테이블 지우고 다시 생성
      ddl-auto: create #자동으로 테이블 만듦
    properties:
      hibername:
        #show_sql: true  #System out으로 출력
        format_sql: true

logging.level:
    #하이버네이트가 생성하는 sql이 보인다 / 로거를 통해 보인다.
  org.hibernate.SQL: debug
  #파라미터 조회
  org.hibernate.type: trace